version: '3'
services:
  mysql-db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mysql-db
